name: Push

on:
  push:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-action
        uses: taiki-e/checkout-action@v1.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build with Gradle
        run: chmod +x ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
         name: Duka.apk
         path: app/build/outputs/apk/debug/app-debug.apk






